CREATE TABLE conference
(
    id                       BIGINT generated by default as identity,
    name                     VARCHAR(255),
    participants_number      INTEGER NOT NULL check (participants_number>=100),
    CONSTRAINT PK_conference PRIMARY KEY (id)
);

INSERT INTO conference (id, name, participants_number) VALUES (1, 'conference1', 101);
